#!/bin/bash

# Auto-Build Environment Setup
# Minesweeper Clone - Desktop Application
# Generated by Planner Agent

set -e

echo "========================================"
echo "Minesweeper Clone - Development Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check Python installation
echo ""
echo "Checking prerequisites..."

if ! command -v python &> /dev/null; then
    echo -e "${RED}Error: Python is not installed${NC}"
    echo "Please install Python 3.8+ from https://python.org"
    exit 1
fi

PYTHON_VERSION=$(python --version 2>&1 | awk '{print $2}')
echo -e "${GREEN}✓ Python $PYTHON_VERSION found${NC}"

# Check Tkinter availability
echo ""
echo "Checking Tkinter (GUI framework)..."

if python -c "import tkinter" 2>/dev/null; then
    echo -e "${GREEN}✓ Tkinter is available (built-in)${NC}"
else
    echo -e "${RED}Error: Tkinter is not available${NC}"
    echo "Tkinter should be included with Python. Please reinstall Python."
    exit 1
fi

# Install dependencies if needed
if [ -f "requirements.txt" ]; then
    echo ""
    echo "Installing Python dependencies..."
    pip install -q -r requirements.txt
    echo -e "${GREEN}✓ Dependencies installed${NC}"
fi

# Run tests if they exist
if [ -d "tests" ] && [ "$(ls -A tests/*.py 2>/dev/null)" ]; then
    echo ""
    echo "Running tests..."
    if pytest tests/ -v; then
        echo -e "${GREEN}✓ All tests pass${NC}"
    else
        echo -e "${YELLOW}Warning: Some tests failed${NC}"
    fi
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Setup Complete!"
echo "========================================"
echo ""
echo "To run the Minesweeper application:"
echo ""
echo -e "${GREEN}  python main.py${NC}"
echo ""
echo "Or run tests:"
echo ""
echo -e "${GREEN}  pytest tests/ -v${NC}"
echo ""
echo "Project Structure:"
echo "  src/models/     - Data structures (Cell, GameState)"
echo "  src/game/       - Game logic (Board, flood fill, chording)"
echo "  src/ui/         - Tkinter interface"
echo "  tests/          - Unit tests"
echo ""
